### ISSUE TITLE
METIS LSS scripts for Wolfgang

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/irdb#167]
To help Wolfgang we should create one (or six) python script(s) that wolfgang can run from the command line that produce the fits files needed by him to investigate the LSF for various observation modes:

Tasks to do:

- [x] (@teutoburg) script(s) to simulate `image_plane` images for LSS with:
	- all effects turned off except atmospheric TERCurve
	- input Source object is a flat spectrum from 3-15µm, 
	- for two spatial objects:
		- point source
		- slit filling extended source (i.e. large image)
	- for filters: L_spec, M_spec, N_spec
	- deliver the image_plane image and ignore the readout crap
	- save the image_plane image to disk

- [x] (@astronomyk) Updated trace geometries for the LSS modes

**Comment by teutoburg** [comment]
Ad 1) Shall the scripts be pushed anywhere or just shared locally?
