### ISSUE TITLE
Ensure Focal Plane Array (FPA) parameters are up to date

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/irdb#28]
Ric created a [technical note about some the Focal Plane Orientation](https://bscw.mpe.mpg.de/bscw/bscw.cgi/5161261?op=preview) (ELT-TRE-MCD-56300-0132, v1.3, dated May 6th 202), that seems to not be incorporated in [MICADO/FPA_array_layout.dat](MICADO/FPA_array_layout.dat), which is from October 2020.

It is not entirely clear what needs to change (if anything indeed needs to change).

@astronomyk can you verify that the MICADO package is up to date with the above note?

**Comment by astronomyk** [comment]
Thanks for reminding me of the document. I haven't read it, so I can not
confirm if the ScopeSim Micado package is up to date. I'll add this to my
to-do list for when I'm back at work.



Hugo Buddelmeijer ***@***.***> schrieb am Fr., 28. Jän. 2022,
14:58:

**Comment by hugobuddel** [comment]
Closed by #32
